# Generated by Django 5.0.4 on 2024-06-24 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_app', '0002_feedback_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='owner',
            field=models.CharField(default='annonymous', max_length=1000),
            preserve_default=False,
        ),
    ]
