# Generated by Django 5.0.4 on 2024-06-30 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_app', '0004_chemmain_compscimain_mathmain_physicsmain'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChemUnit',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study_app.chemmain')),
            ],
        ),
        migrations.CreateModel(
            name='ChemSubUnit',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study_app.chemunit')),
            ],
        ),
        migrations.CreateModel(
            name='CompSciUnit',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study_app.compscimain')),
            ],
        ),
        migrations.CreateModel(
            name='CompSciSubUnit',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study_app.compsciunit')),
            ],
        ),
        migrations.CreateModel(
            name='MathUnit',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study_app.mathmain')),
            ],
        ),
        migrations.CreateModel(
            name='MathSubUnit',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study_app.mathunit')),
            ],
        ),
        migrations.CreateModel(
            name='PhysicsUnit',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study_app.physicsmain')),
            ],
        ),
        migrations.CreateModel(
            name='PhysicsSubUnit',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study_app.physicsunit')),
            ],
        ),
    ]
