# Generated by Django 5.0.4 on 2024-07-03 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_app', '0008_multiplechoicequestion_multiplechoicechoice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiplechoicechoice',
            name='correct',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='MultipleChoiceAnswer',
        ),
    ]
