# Generated by Django 5.0.4 on 2024-07-03 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_app', '0009_multiplechoicechoice_correct_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultipleChoiceQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=250)),
                ('number_of_questions', models.IntegerField(default=3)),
                ('required_score_to_pass', models.IntegerField(default=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='multiplechoicequestion',
            name='unit',
        ),
    ]
