# Generated by Django 5.0.4 on 2024-07-03 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_app', '0011_alter_multiplechoicequiz_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiplechoicequiz',
            name='number_of_questions',
            field=models.IntegerField(default=4),
        ),
    ]
