# Generated by Django 5.0.4 on 2024-07-04 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_app', '0012_alter_multiplechoicequiz_number_of_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiplechoicequestion',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='study_app.multiplechoicequiz'),
        ),
    ]
