# Generated by Django 4.2.13 on 2024-07-15 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_app', '0016_alter_chemmain_image_alter_compscimain_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemsubunit',
            name='image',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
        migrations.AddField(
            model_name='compscisubunit',
            name='image',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
        migrations.AddField(
            model_name='mathsubunit',
            name='image',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
        migrations.AddField(
            model_name='physicssubunit',
            name='image',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
    ]
